In [1]:
print("Modules / Read-Write Ops / Numpy")

Modules / Read-Write Ops / Numpy


In [ ]:
#read from file
with open('Practice.txt') as practiceFile:
 contents = practiceFile.read()
 print(contents)

In [ ]:
#read from folder's file
with open('Practice Folder/Practice2.txt') as practiceFile:
 contents = practiceFile.read()
 print(contents)

In [17]:
# filepath
filePath= 'Practice Folder/Practice2.txt'
with open(filePath) as practiceFile:
 contents = practiceFile.read() 
 print(contents)

Umar
Aslam
Nawab


In [29]:
#line by line

filepath='Practice.txt'
with open(filepath) as PracticeFile:
    for oneLine in PracticeFile:
        print(oneLine)

123
456
789


In [114]:
#accessing from outside the scope

with open('Practice.txt') as PracticeFile:
    contents = PracticeFile.readlines()

for line in contents:
    print(line.rstrip())

000
111
222


In [63]:
#entire file in one-line

filepath = 'Practice.txt'
with open(filepath) as PracticeFile:
 lines = PracticeFile.readlines()

oneline=""

for line in lines:
 oneline += line.rstrip()

print(oneline)


123456789


In [64]:
#liminting content

filepath = 'Practice.txt'
with open(filepath) as PracticeFile:
 lines = PracticeFile.readlines()

oneline=""

for line in lines:
 oneline += line.rstrip()

print(oneline[:6] + " "+ "still continue")
print(len(oneline))

123456 still continue
9


In [87]:
#writing to a file

filepath= 'Practice.txt'

with open(filepath,'w') as PracticeFile:
    PracticeFile.write('000 \n') # \n when use multi-line
   # PracticeFile.write("111") #for multi-line



In [88]:
filepath= 'Practice.txt'

with open(filepath) as PracticeFile:
    contents=PracticeFile.read()
    print(contents)

000 



In [89]:
#appending to file 

filepath= 'Practice.txt'

with open(filepath,'a') as PracticeFile:
    PracticeFile.write('222')

In [91]:
filepath= 'Practice.txt'

with open(filepath) as PracticeFile:
    contents=PracticeFile.read()
    print(contents)

000 
222


In [95]:
#exception cases - zero division

firstnum=5
secondnum=0

try:
    answer= firstnum/secondnum
    
except ZeroDivisionError:
    print("Your number should not be divide by 0")

else:
    print(answer)
    


Your number should not be divide by 0


In [116]:
try:
    with open('Practice Folder/Practice2.txt') as practiceFile:
             contents = practiceFile.read()
            
except FileNotFoundError:
    print("your file is not present in the directory")
 
else:
    print(contents)

//ye practice ke folder main ha

Umar
Aslam
Nawab


In [146]:
import math

print(math.pi)

3.141592653589793


In [152]:
import math as mymath
print(mymath.pi)

3.141592653589793


In [148]:
from math import pi
print(pi)

3.141592653589793


In [3]:
from math import *
print(e)


2.718281828459045


In [9]:
import math 
print(math.ceil(5.7))
print(math.floor(5.7))

6
5


In [7]:
#import import_ipynb

import import_ipynb

import Practice2

Practice2.add(3,5)



8

In [23]:
#csv example

import csv

with open("data.csv") as PracticeFile:
    contents=csv.reader(PracticeFile)
    for line in contents:
        print(line)



['\ufeffProgramming language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido van Rossum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [56]:
#numpy start

import numpy as np
data = np.random.randn(2, 3)
print(data ,'\n') 
print(data+data , '\n') 
print(data * 10 , '\n')
print(data.shape, '\n')
print(data.dtype , '\n')
print(data.ndim, '\n')


[[-0.50869503 -0.41723618 -1.43898378]
 [ 0.80754767  0.4373393  -0.51302052]] 

[[-1.01739007 -0.83447235 -2.87796756]
 [ 1.61509535  0.87467861 -1.02604104]] 

[[ -5.08695035  -4.17236176 -14.38983779]
 [  8.07547674   4.37339304  -5.13020518]] 

[[-3.9316287  -4.79344821 -1.38986973]
 [ 2.47663397  4.5731083  -3.89847956]] 

(2, 3) 

float64 

2 



In [45]:
#zero and empty

print(np.zeros(10) , "\n")

print(np.zeros((3,6)), "\n")

print(np.zeros((2,3,6)), "\n")


print(np.empty((3,6)) , "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [96]:
#arrange - like range in normal python

print(np.arange(9), "\n")
print(np.arange(16).reshape(4,4))


[0 1 2 3 4 5 6 7 8] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [55]:
#changing data type
arr = np.array([1,2,3,4,5])
print(arr.astype(np.float64))

arr2= np.array(["1","2","3","4","5"])
print(arr2.astype(np.float64))

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [106]:
#operations on array and datatype

arr = np.array([4,2,6,8,] , dtype='int64')
print(arr * 2 ,'\n')
print(arr * arr ,'\n')
print(2/arr  ,'\n')
print(arr ** 2 ,'\n')
print(np.sqrt(arr) , '\n')
print(np.exp(arr) , '\n')
print(np.mean(arr) , '\n')
print(np.sort(arr) , '\n')
print(np.sum(arr) , '\n')
print(np.cumsum(arr) , '\n')


arr2= np.array([1,2,3,4])

print(arr > arr2)

[ 8  4 12 16] 

[16  4 36 64] 

[0.5        1.         0.33333333 0.25      ] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

[2 4 6 8] 

20 

[ 4  6 12 20] 

[ True False  True  True]


In [72]:
# indexing and slicing

arr=np.arange(10)
print(arr)
9
arr2=arr[5:8]
print(arr2)

arr[:3]=0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [108]:
#boolean example --imp- the number of array and names shoule be same

namesArr= np.array(["Umar", "Umair", "Nouroz", "Ali","Umar"])
numArr=np.random.randn(5,3)
print(numArr , '\n')
print(namesArr , '\n')
print(namesArr == "Umar" , '\n')
print(numArr[namesArr=="Umar"] , '\n')
print(numArr[~(namesArr=="Umar")], '\n')
print(np.unique(namesArr),'\n')

[[-1.48996757  0.67436014 -0.29397452]
 [ 0.01436092  0.04158438 -1.36624663]
 [ 1.15214238 -0.63827616  1.94497463]
 [ 0.50279099  1.30619832  1.49055136]
 [ 0.30689239 -0.09440126 -1.25076309]] 

['Umar' 'Umair' 'Nouroz' 'Ali' 'Umar'] 

[ True False False False  True] 

[[-1.48996757  0.67436014 -0.29397452]
 [ 0.30689239 -0.09440126 -1.25076309]] 

[[ 0.01436092  0.04158438 -1.36624663]
 [ 1.15214238 -0.63827616  1.94497463]
 [ 0.50279099  1.30619832  1.49055136]] 

['Ali' 'Nouroz' 'Umair' 'Umar'] 



In [102]:
arr1= np.random.randn(4)
print(arr1 , '\n')
arr2= np.random.randn(4)
print(arr2 , '\n')
print(np.maximum(arr1,arr2), '\n')
print(np.minimum(arr2,arr1), '\n')

[-1.31219923  0.3114249  -0.64400874 -0.0641869 ] 

[ 0.14812246 -0.53896025  0.05679158 -0.33127801] 

[ 0.14812246  0.3114249   0.05679158 -0.0641869 ] 

[-1.31219923 -0.53896025 -0.64400874 -0.33127801] 

